<div class="slide"></div>
<h2>Entrez vos identifiants</h2>
    <form method="post" action="<?= $requestUrl ?>/admin">
        <fieldset>
            <input type="text" name="pseudo" id="pseudo" placeholder="Identifiant">
            <input type="password" name="password" id="password" placeholder="Mot de passe">
        </fieldset>
        <span class="boutons"><input type="submit" id="connect" value="Se connecter"/><input type="reset" value="Effacer"/></span>
    </form>

